/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    'City': '城市',
    'Colors': '颜色',
    'Dark Blue': '深蓝色',
    'Dark Purple': '深紫色',
    'Dark Red': '深红色',
    'Direction': '方向',
    'Green': '绿色',
    'Light Blue': '淡蓝色',
    'Light Brown': '淡棕色',
    'Light Purple': '淡紫色',
    'Light Yellow': '淡黄色',
    'Map Editor': '地图编辑器',
    'Medium Blue': '中蓝色',
    'Medium Purple': '中紫色',
    'Navy Blue': '海军蓝',
    'Neon': '霓虹',
    'Neon Pink': '霓虹粉色',
    'Status': '状态',
    'Tiles': '砖块',
    'Special': '特殊',
    'Orange': '橙色',
    'Pale Green': '浅绿色',
    'Pale Yellow': '浅黄色',
    'up': '上',
    'down': '下',
    'left': '左',
    'right': '右',
    'Utilities': '实用工具',
    'Yellow': '黄色',
    'Decorative': '装饰',
    'Paths': '路径',
    'Pink': '粉色',
    'Purple': '紫色',
    'Space': '太空',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    '': '',
    '': '',

}


//需处理的前缀
var cnPrefix = {
    "(-": "(-",
    "(+": "(+",
    "(": "(",
    "-": "-",
    "+": "+",
    " ": " ",
    ": ": "： ",
    "\n": "",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": "",
    //树游戏
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    'Auto-Pathfind (': '自寻路（',
    "Clear Display (": "清除显示（",
    "Clear Pathfinding (": "清除寻路（",
    "Clear Spawns (": "清除出怪 (",
    "Left (left": "左 (左",
    "Left Corner (": "左角 (",
    "Mouse: (": "鼠标: (",
    "No Path (": "无路径 (",
    "Road Tile (": "道路砖块 (",
    "Sidewalk (": "人行道 (",
    "Tower Tile (": "塔砖块 (",
    "Up (": "向上 (",
    "Turn Autogen Off (": "闭自动生成 (",
    "Up Path (": "向上路径 (",
    "Wall Tile (": "墙砖 (",
    "None (": "无 (",
    "Import map (": "导入地图 (",
    "Export map (": "导出地图 (",
    "Exit Point (": "出口点（",
    "Empty Tile (": "空砖 (",
    "Fill Selected (": "填充所选 (",
    "Grass (": "草 (",
    "Display Paths (": "显示路径 (",
    "Left Path (": "左路径 (",
    "Reset Map (": "重置地图 (",
    "Reset Zoom (": "重置缩放 (",
    "Right (": "右 (",
    "Right Corner (": "右角 (",
    "Right Path (": "右路径 (",
    "Spawnpoint (": "出怪点 (",
    "Update Display (": "更新显示 (",
    "Dim: ": "没有: ",
    "Enemy-Only Tile (": "仅限敌人的图块 (",
    "Path Tile (": "路径砖块 (",
    "Down Path (": "下路径 (",
    "Down (": "下 (",
    "Display Mode (": "显示模式 (",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀
var cnPostfix = {
    ":": "：",
    "：": "：",
    ": ": "： ",
    "： ": "： ",
    "/s)": "/s)",
    "/s": "/s",
    ")": ")",
    "%": "%",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": " ",
    "\n": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^([\d\.]+)e(\d+)$/,
    /^([\d\.]+)$/,
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
var cnRegReplace = new Map([
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
	[/^([\d\.]+)\/sec$/, '$1\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^(\d+) Royal points$/, '$1 皇家点数'],
    [/^Cost: (\d+) RP$/, '成本：$1 皇家点数'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);